<?php

return [
    'PT Sulawesi Cahaya Mineral',
    'PT Prima Utama Sultra',
    'PT Intertek Utama Services',
    'PT Anugerah Batu Putih',
    'PT Serasi Auto Raya',
    'PT Merdeka Mining Services',
    'PT Uniteda Arkato',
    'PT Garda Utama Nasional',
    'PT Carsurin',
    'PT Mulia Rentalindo Persada',
    'PT Satria Jaya Sultra',
    'PT Putra Morowali Sejahtera',
    'PT Transkon Jaya',
    'PT Mitra Usaha Katiga',
    'PT Bagong Dekaka Makmur',
    'PT Jakarta Anugerah Mandiri',
    'PT Malachite International Mining',
    'PT Sumber Semeru Indonesia',
    'PT Surveyor Carbon Consulting Indonesia',
    'PT Aneka Kimia Raya',
    'PT Hillcon Jaya Sakti',
    'PT Karyaindo Ciptanusa',
    'PT Roda Jaya Sakti',
    'PT Sinar Terang Mandiri',
    'PAM OBVIT ( POLISI )',
    'CTCE Group',
    'PT. QMB',
    'VISITOR',
    'PT Teknologi Infrastruktur Indonesia',
    'PT Andalan Duta Eka Nusantara',
    'PT Petronesia Benimel',
    'PT Mitra Ateda Selaras',
    'PT Tiga Putra Bungoro',
    'PT Superkrane Mitra Utama',
    'PT Presisi Digital Moderen Teknologi',
    'MCC',
    'PT INTIMAP INDONESIA',
    'PT BLASTPRO',
    'PT TECTONA MITRA UTAMA',
    'PT TOWER BERSAMA GROUP',
    'PT BUMINDO MULIA MANDIRI',
    'PT CAHAYAMEGAH KARUNIA BERSAMA',
    'PT SAMUDRA MULIA ABADI',
    'PT ASIATRUST TECHNOVIMA',
    'PT LANCAR JAYA MANDIRI ABADI',
    'PT WIRATMAN',
    'PT KOPERASI',
    'PT CAKRAWALA ENERGI KONSTRUKSI',
    'PT AMAZON WEB SERVICES',
    'PT INTI KARYA PASIFIK',
    'PT REAL',
    'PT SUCOFINDO',
    'PT LAPI',
    'PT SOL',
    'PT TMI',
];
